github_repo_url: "https://github.com/sua-conta/seu-repo.git"
github_repo_url_fallback: "git@github.com:sua-conta/seu-repo.git"
local_clone_path: "/tmp/repositorio-clonado"
fallback_clone_path: "/tmp/repositorio-clonado-fallback"