---
- name: "PLAYBOOK LEX - ORQUESTRAÇÃO"
  hosts: "{{ hostname | default('localhost') }}"
  gather_facts: false
  become: false
  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/deploy_bot.yml
      tags: deploy_bot

    - import_tasks: tasks/list_bot.yml
      tags: list_bots

    # - name: "🧾 Listar todos os bots"
    #   shell: ./scripts/list-bots.sh
    #   register: list_bots_output
    #   changed_when: false
    #   tags: list_bots

    # - name: "🔍 Exibir bots disponíveis"
    #   debug:
    #     var: list_bots_output.stdout_lines
    #   tags: list_bots
    
    # - name: "🎯 Selecionar o bot desejado"
    #   pause:
    #     prompt: "Digite o nome exato do bot que você quer selecionar:"
    #   register: selected_bot
    #   tags: list_bots

    # - name: "✅ Bot selecionado"
    #   debug:
    #     msg: "Você selecionou o bot: {{ selected_bot.user_input }}"
    #   tags: list_bots

    # - name: "📌 Salvar bot escolhido"
    #   set_fact:
    #     bot_name_selected: "{{ selected_bot.user_input }}"

    - import_tasks: tasks/export_bot.yml
      tags: export_bot
  
  
    # - name: "📦 Exportar bot escolhido"
    #   shell: ./scripts/export-bot.sh "{{ bot_name_selected }}"
    #   when: export_enabled | default(false)
    #   tags: export_bot
    
    # - name: "📂 Verificar se o bot foi exportado"
    #   stat:
    #     path: "bot-export.zip"
    #   register: export_check
    #   when: export_enabled | default(false)

    # - name: "📋 Exibir resultado da exportação
    #   debug:
    #     msg: "O bot foi exportado com sucesso: {{ export_check.stat.exists }}"
    #   when: export_enabled | default(false)
    #   tags: export_bot
    

    - import_tasks: tasks/import_bot.yml
      tags: import_bot


    # - name: "📥 Verificar se o bot exportado existe"
    #   stat:
    #     path: "bot-export.zip"
    #   register: import_check
    #   when: import_enabled | default(false)
    #   tags: import_bot
    
    # - name: "📥 Importar bot exportado"
    #   shell: ./scripts/import-bot.sh
    #   when: import_enabled | default(false)
    #   tags: import_bot

    # - name: "🚀 Fazer deploy do bot (versão + alias)"
    #   shell: ./scripts/post-import-bot.sh
    #   when: deploy_enabled | default(false)
    #   tags: deploy_bot
