- name: "PLAYBOOK LEX - ORQUESTRAÇÃO"
  hosts: "{{ hostname | default('localhost') }}"
  gather_facts: true
  become: false
  vars_files:
    - vars/main.yml
    - vars/config.yml

  tasks:
    
    # # 📝 Etapa de validação de pré-requisitos
    # - import_tasks: tasks/validate_prerequisites.yml
    #   tags: [validate_prerequisites]
    
    # Authentication AWS
    - name: "🔑 Autenticação AWS"
      import_tasks: tasks/auth-AWS/main.yml
      tags: [auth,deploy,destroy]

    # 🔑 Etapa configuração Checkout
    - import_tasks: tasks/checkout/main.yml
      tags: [checkout,deploy,destroy]
    
    # 📦 Etapa de Deploy (ex: criar bot, intents, slots, etc)
    - import_tasks: tasks/terraform-deploy/main.yml
      tags: [deploy_terraform, deploy]

    # 📦 Etapa de Destroy (ex: criar bot, intents, slots, etc)
    - import_tasks: tasks/terraform-destroy/main.yml
      tags: [destroy_terraform, destroy]

    # 🧾 Etapa de listagem de bots (se quiser reativar depois)
    # - import_tasks: tasks/list_bot.yml
    #   tags: [list_bots]

    # 📤 Criação do alias bot
    - import_tasks: tasks/pos-import/main.yml
      tags: [deploy_terraform, deploy, pos_import]

    # # 📥 Importação do bot na conta destino
    # - import_tasks: tasks/import_bot.yml
    #   tags: [import_bot]

    # ✅ Mensagem final
    - name: "✅ Mensagem de conclusão"
      debug:
        msg: "Playbook de orquestração do Amazon Lex concluído com sucesso!"
      tags: [deploy_terraform, deploy, destroy]