---
- name: Exportar e importar bot Amazon Lex
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/credentials.yml
    - vars/config.yml

  tasks:

    - name: Configura credenciais AWS temporárias
      set_fact:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_REGION: "{{ aws_region }}"

    - name: Define variáveis de ambiente para autenticação AWS
      shell: |
        export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
        export AWS_DEFAULT_REGION={{ AWS_REGION }}
        aws lexv2-models start-export \
          --resource-specification file://{{ lex_spec_file }} \
          --file-format LexJson \
          --export-s3-bucket {{ s3_bucket }} \
          --export-s3-prefix lex-exports/
      environment:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ AWS_REGION }}"
      tags: export

    - name: Pausa para garantir exportação
      pause:
        seconds: 20

    - name: Baixa o artefato do S3 exportado
      shell: |
        aws s3 cp s3://{{ s3_bucket }}/lex-exports/{{ export_file_name }} /tmp/{{ export_file_name }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ AWS_REGION }}"
      tags: export

    - name: Importa bot na outra conta
      shell: |
        export AWS_ACCESS_KEY_ID={{ dest_aws_access_key }}
        export AWS_SECRET_ACCESS_KEY={{ dest_aws_secret_key }}
        export AWS_DEFAULT_REGION={{ dest_aws_region }}
        aws lexv2-models start-import \
          --payload fileb:///tmp/{{ export_file_name }} \
          --merge-strategy Overwrite
      environment:
        AWS_ACCESS_KEY_ID: "{{ dest_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ dest_aws_secret_key }}"
        AWS_DEFAULT_REGION: "{{ dest_aws_region }}"
      tags: import