- name: Verificar se o Terraform já está instalado
  ansible.builtin.command: terraform --version
  register: terraform_version
  ignore_errors: yes

- name: Informar que o Terraform já está instalado
  ansible.builtin.debug:
    msg: "Terraform já está instalado: {{ terraform_version.stdout_lines[0] }}"
  when: terraform_version.rc == 0

- name: Informar que o Terraform não está instalado e iniciar download
  ansible.builtin.debug:
    msg: "Terraform não está instalado. Iniciando download e instalação..."
  when: terraform_version.rc != 0

- name: Instalar Terraform se não existir
  ansible.builtin.shell: |
    curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    mv terraform /usr/local/bin/
  when: terraform_version.rc != 0

- name: "Clonar repositório do Terraform"
  ansible.builtin.git:
    repo: "{{ terraform_repo_url }}"
    dest: ./terraform/
    version: main
  tags: git

# - name: "Atualiza valores do TFVARS"
#   ansible.builtin.template:
#     src: templates/terraform.tfvars.j2
#     dest: ./terraform/terraform.tfvars
#   tags: tfvars
  
- name: Inicializar Terraform
  ansible.builtin.command:
    cmd: terraform init
    chdir: "{{ terraform_dir }}"
  tags: terraform_init

- name: Executar Terraform Plan
  ansible.builtin.command:
    cmd: terraform plan -var-file="{{ terraform_dir }}"/terraform.tfvars
    chdir: "{{ terraform_dir }}"
  tags: terraform_plan

# - name: Aplicar Terraform
#   ansible.builtin.command:
#     cmd: terraform apply -auto-approve tfplan
#     chdir: /caminho/para/seu/infra
