- name: "🧾 Listar todos os bots do Amazon Lex V2 (formato tabela)"
  shell: >
    aws lexv2-models list-bots
    --region {{ aws_region }}
    --profile {{ aws_profile }}
    --query "botSummaries[].{Name:botName,ID:botId,Status:botStatus}"
    --output table
  register: list_bots_output
  changed_when: false
  tags: listar_bots

- name: "🔍 Exibir bots disponíveis"
  debug:
    var: list_bots_output.stdout_lines

- name: "🎯 Selecionar o bot desejado"
  pause:
    prompt: "Digite o nome exato do bot que você quer selecionar:"
  register: selected_bot

- name: "✅ Bot selecionado"
  debug:
    msg: "Você selecionou o bot: {{ selected_bot.user_input }}"

- name: "📌 Salvar bot escolhido"
  set_fact:
    bot_name_selected: "{{ selected_bot.user_input }}"