---
# task para limpar diretorio antes de clonar repositório
- name: Limpar diretório local antes de clonar repositório
  file:
    path: "{{ local_clone_path }}"
    state: absent
    force: yes
  register: cleanup_result

# Clonar repositório do GitHub
- name: Clonar repositório do GitHub
  git:
    repo: "{{ github_repo_url }}"
    dest: "{{ local_clone_path }}"
    version: main
    force: yes
  register: git_clone_result
#  failed_when: git_clone_result.failed is defined
  notify: retry clone with alternative method

- name: Validar se o clone foi bem-sucedido
  assert:
    that:
      - git_clone_result is defined
      - git_clone_result.failed is not defined
      - git_clone_result.after is defined
    fail_msg: "Falha ao clonar o repositório. Tentativa alternativa será executada pelo handler."
    success_msg: "Repositório clonado com sucesso."

- name: Exibir detalhes do resultado do clone
  debug:
    var: git_clone_result

