---
- name: Playbook modular com roles especializadas
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    github_repo_url: "https://github.com/sua-conta/seu-repo.git"
    local_clone_path: "/tmp/repositorio-clonado"
    aws_profile: "default"
    aws_region: "us-east-1"

  roles:
    - role: github_checkout
      vars:
        repo_url: "{{ github_repo_url }}"
        clone_path: "{{ local_clone_path }}"
      tags: ['checkout']

    # - role: github_checkout
    # - { role: aws_auth, tags: ['aws'] }
    # - { role: terraform_exec, tags: ['terraform'] }
    # - { role: resumo_final, tags: ['resumo'] }
