# Configuration variables for Terraform automation with Amazon Lex
branch_repo: "main"
terraform_dir: "./terraform-repo/"
project_name: "amazon-lex-automation"
environment: "hml"
region: "us-east-1"
aws_assume_role_arn: "arn:aws:iam::743065069150:role/CrossAccountMasterRole"
backend_bucket: "samequemendes-terraform-tf-states"
backend_key: "amazon-lex/terraform.tfstate"
backend_region: "us-east-1"
#bot_name: "WMZQH0M4SQ-importado"
role_arn: "arn:aws:iam::743065069150:role/poc-role-amazon-lex-sameque-mendes"
var_file: "variables/hml.tfvars"

# GitHub repository configuration
github_repo_url: "https://github.com/samequemendes/amazon-lex-v2-example.git"
github_repo_url_fallback: "git@github.com:samequemendes/amazon-lex-v2-example.git"
local_clone_path: "./terraform-repo"
fallback_clone_path: "./terraform-repo-fallback"