terraform_repo_url: "https://github.com/samequemendes/terraform-aws-lex-examples.git"
branch: "main"
terraform_dir: "./terraform/"
project_name: "amazon-lex-automation"
environment: "hml"
region: "us-east-1"
profile_AWS: "AdministratorAccess-022499044898"
backend_bucket: "samequemendes-terraform-tf-states"
backend_key: "amazon-lex/terraform.tfstate"
backend_region: "us-east-1"