---
# Assumir Role na AWS
- name: Assume Role in AWS na conta destino
  sts_assume_role:
    role_arn: "{{ prefix_iam }}{{ dest_account_id }}:role/{{ role_name }}"
    role_session_name: "Ansible-Lex-Session-migracao"
    aws_profile: "AgentAssumeRole-022499044898"
  register: dest_assumed_role

- name: configurar credenciais temporárias da conta AWS Destino
  set_fact:
    aws_access_key: "{{ dest_assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ dest_assumed_role.sts_creds.secret_key }}"
    aws_session_token: "{{ dest_assumed_role.sts_creds.session_token }}"

# Exibe credenciais recebidas
- name: Exibir credenciais temporárias da Conta AWS Destino
  debug:
    msg: "Access Key: {{ aws_access_key }}, Secret Key: {{ aws_secret_key }}, Session Token: {{ aws_session_token }}"
