---
- name: "Atualiza valores do TFVARS"
  ansible.builtin.template:
    src: templates/hml.tfvars.j2
    dest: "{{ local_clone_path }}/variables/{{ env }}.tfvars"
  tags: ["cnfg_terraform" , "deploy_bot"]

- name: Define configurações de backend do Terraform
  ansible.builtin.template:
    src: templates/backend.tf.j2
    dest: "{{ local_clone_path }}/backend.tf"
  tags: ["cnfg_terraform" , "deploy_bot"]

- name: Checar quem sou eu com AWS CLI
  shell: aws sts get-caller-identity
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
  register: identity_result

- debug:
    msg: "{{ identity_result.stdout }}"

# Terraform Apply Modulo Community
- name: Executar Terraform Apply no modulo community
  community.general.terraform:
    project_path: "{{ local_clone_path }}"
    state: present
    force_init: true
    backend_config:
      bucket: "its-on-terraform-tf-states"
      key: "terraform-states/lexv2/terraform.tfstate"
      region: "us-east-1"
    lock: false
    variables_files: "{{ var_file }}"
  tags: ["terraform_apply", "deploy_bot"]
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"

# - name: Inicializar Terraform
#   ansible.builtin.command:
#     cmd: terraform init -no-color
#     chdir: "{{ local_clone_path }}/"
#   tags: ["deploy_bot", "destroy_bot"]
#   environment:
#     AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
#     AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
#     AWS_SESSION_TOKEN: "{{ aws_session_token }}"

# - name: 📦 Executar Terraform Plan
#   ansible.builtin.shell: "TF_IN_AUTOMATION=true terraform plan -var-file={{ var_file }}"
#   args:
#     chdir: "{{ local_clone_path }}/"
#   register: terraform_plan_result
#   ignore_errors: true
#   tags: ["terraform_plan", "deploy_bot"]
#   environment:
#     AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
#     AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
#     AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    
# - name: 📄 Mostrar STDOUT (resultado do plan)
#   debug:
#     var: terraform_plan_result.stdout_lines
#   tags: ["terraform_plan", "deploy_bot"]

# - name: ❌ Mostrar STDERR (caso erro)
#   debug:
#     var: terraform_plan_result.stderr_lines
#   when: terraform_plan_result.rc != 0
#   tags: ["terraform_plan", "deploy_bot"]

# - name: 📦 Executar Terraform Apply
#   ansible.builtin.shell: "TF_IN_AUTOMATION=true terraform apply -var-file={{ var_file }} -auto-approve"
#   args:
#     chdir: "{{ local_clone_path }}/"
#   register: terraform_apply_result
#   ignore_errors: true
#   tags: ["terraform_apply", "deploy_bot"]
#   environment:
#     AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
#     AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
#     AWS_SESSION_TOKEN: "{{ aws_session_token }}"

# - name: 📄 Mostrar STDOUT (resultado do apply)
#   debug:
#     var: terraform_apply_result.stdout_lines
#   tags: ["terraform_apply", "deploy_bot"]

# - name: ❌ Mostrar STDERR (caso erro)
#   debug:
#     var: terraform_apply_result.stderr_lines
#   when: terraform_apply_result.rc != 0
#   tags: ["terraform_apply", "deploy_bot"]


# # terraform destroy

# - name: 📦 Executar Terraform Destroy sem ANSI
#   ansible.builtin.shell: |
#     "TF_IN_AUTOMATION=true terraform destroy -var-file={{ var_file }}"
#   args:
#     chdir: "{{ local_clone_path }}/ "
#   register: terraform_destroy_result
#   ignore_errors: true
#   tags: ["terraform_destroy", "destroy_bot"]

# - name: 📄 Mostrar STDOUT (resultado do destroy)
#   debug:
#     var: terraform_destroy_result.stdout_lines
#   tags: ["terraform_destroy", "destroy_bot"]

# - name: ❌ Mostrar STDERR (caso erro)
#   debug:
#     var: terraform_destroy_result.stderr_lines
#   when: terraform_destroy_result.rc != 0
#   tags: ["terraform_destroy", "destroy_bot"]
