---
- name: "Atualiza valores do TFVARS"
  ansible.builtin.template:
    src: templates/hml.tfvars.j2
    dest: "{{ local_clone_path }}/variables/{{ env }}.tfvars"
  tags: ["cnfg_terraform" , "deploy_bot"]

- name: Define configurações de backend do Terraform
  ansible.builtin.template:
    src: templates/backend.tf.j2
    dest: "{{ local_clone_path }}/backend.tf"
  tags: ["cnfg_terraform" , "deploy_bot"]

- name: Checar quem sou eu com AWS CLI
  shell: aws sts get-caller-identity
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
  register: identity_result

- debug:
    msg: "{{ identity_result.stdout }}"

# Terraform Apply Modulo Community
# - name: Executar Terraform Apply no modulo community
#   community.general.terraform:
#     project_path: "{{ local_clone_path }}"
#     state: present
#     force_init: true
#     backend_config:
#       bucket: "its-on-terraform-tf-states"
#       key: "terraform-states/lexv2/terraform.tfstate"
#       region: "us-east-1"
#     lock: false
#     variables_files: "{{ var_file }}"
#   tags: ["terraform_apply", "deploy_bot"]
#   environment:
#     AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
#     AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
#     AWS_SESSION_TOKEN: "{{ aws_session_token }}"

- block:
    # Terraform Apply Módulo Community
    - name: Executar Terraform Apply no modulo community
      community.general.terraform:
        project_path: "{{ local_clone_path }}"
        state: present
        force_init: true
        backend_config:
          bucket: "its-on-terraform-tf-states"
          key: "terraform-states/lexv2/terraform.tfstate"
          region: "us-east-1"
        lock: false
        variables_files: "{{ var_file }}"
      register: tf_result
      tags: ["terraform_apply", "deploy_bot"]
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
        AWS_SESSION_TOKEN: "{{ aws_session_token }}"

    - name: Definir bot_id a partir do apply (se disponível)
      set_fact:
        bot_id: "{{ tf_result.outputs.bot_id.value | trim }}"
      when: tf_result.outputs is defined and ('bot_id' in tf_result.outputs)

    # Imprime ID do Bot
    - name: Imprimir ID do Bot
      ansible.builtin.debug:
        msg: "bot_id = {{ bot_id }}"
      when: tf_result.outputs is defined and ('bot_id' in tf_result.outputs)
    

  rescue:
    - name: Terraform falhou — notificar handler para limpar e tentar novamente
      ansible.builtin.debug:
        msg: "Terraform falhou; limpando diretórios e reexecutando..."
      notify: "retry_terraform"

    - name: Rodar handlers imediatamente
      ansible.builtin.meta: flush_handlers
