---
# Assumir Role na AWS
- name: Assume Role in AWS
  sts_assume_role:
    role_arn: "{{ aws_assume_role_arn }}"
    role_session_name: "Ansible-Lex-Session"
    aws_profile: "AgentAssumeRole-022499044898"
  register: assumed_role

- name: configurar credenciais temporárias da AWS
  set_fact:
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    aws_session_token: "{{ assumed_role.sts_creds.session_token }}"

# Exibe credenciais recebidas
- name: Exibir credenciais temporárias da AWS
  debug:
    msg: "Access Key: {{ aws_access_key }}, Secret Key: {{ aws_secret_key }}, Session Token: {{ aws_session_token }}"
